### ISSUE TITLE
Same ability has different damage?!

### ISSUE THREAD

**Issue by Kingdud** [Gaboros/VenturePlan#17]
![335 - Errant Package-2](https://user-images.githubusercontent.com/20249763/125150284-47768300-e104-11eb-902a-fff852a7c377.png)

I see you already have Errant Package in the repo. But when I checked my own spells against what is set in this mod, none of the values line up. Errant Package does more damage in my game client than the mod thinks it does. Overload does a +140dmg bonus in my game client vs the +40 set in the mod. Etc. Does anyone have any ideas why? The mission I am trying to run is Unexpected Delays - level 60. I'm Night Fae and all my NPCs are 60 except the newest one (he's 25, but not on this mission).

**Comment by Kingdud** [comment]
To further add to this confusion, numbers for my own followers are wrong. Take https://www.wowhead.com/adventure-combatant-ability/forests-touch-102 for example. In the mod it's supposed to have 30dmg but my follower does 84? Am I failing to understand something? Or are almost all the values in this mod off (for how well it worked pre 9.1, I'm shocked if they are all this far off.)

**Comment by Gaboros** [comment]
You can't write in the value directly. You have to get the base damage and divide it with the ability damage then multiply it by 100. This is because of the level differences. For example on Emptied mug I have encountered different levels. Base damage 59 and spell damage 88. Later 61-91. Applying the formula:

(91 / 61) * 100 ~= 150
(88 / 59) * 100 ~= 150

In image the ability damage is 56 and the base damage is 140.

(56 / 140) * 100 ~= 40.

**Comment by Kingdud** [comment]
Ok. How do I find the base damage?
